name = "botles"
main = "src/index.js"
compatibility_date = "2026-02-07"

# =========================
# Bindings
# =========================

# KV untuk registrasi user, log, broadcast
kv_namespaces = [
  { binding = "BOT_KV", id = "7b02b00ab9e4420dae019b2024f53d34", preview_id = "7b02b00ab9e4420dae019b2024f53d34" }
]

# (Opsional) Workers Analytics Engine untuk event log 
[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "telegram_bot_activity"

# (Opsional) variabel non-rahasia
# [vars]
# ADMIN_CHAT_ID = "6968439759"
